.TH gyges 1 2013-Jan "linux" "heatherly custom tools manual"

.SH NAME
gyges_hekatonkheires \- wicked, powerful, technical spreadsheet

.SH IMAGERY (see HERITAGE at bottom for more)
ugly, impossibly powerful, one-hundred handed, fifty headed giant

.SH SUMMARY
gyges (j-eye-j-ees) is a light, clean, powerful, technical, aesthetic, and
keyboard-centric console spreadsheet focused on functionality, analytics,
interfacing, scripting, and tailored usage.

.SH SYNOPSIS

.B gyges [OPTIONS]
.nf
primary production version

.B gyges_debug [URGENTS] [OPTIONS]
.nf
performs all production actions, but with debugging and tracing

.SH OPTIONS
.B screen layout.  
gyges can adapt its display in many interesting ways, both size and contents.
rather than list the options here, gyges can tell you its latest.  these options
are non-destructive, so you can play with them without consequence.

.B --layout-options
.RS 8
display options for status, command, and formula and exit.
.RE

.B (:layout options)
.RS 8
display info window for status, command, and formula options.
.RE

.SH SEE ALSO
this documentation is layered to provide easier navigation.
   gyges (1), initiation, options, and structure
   gyges (5), structure of the gyges spreadsheet file
   gyges (6), interactive system usage and navigation
   gyges (7), decision rationale, objectives, and overview
   yVIKEYS, undestanding the VIKEYS standard
   yURG, understanding the available tracing and debugging

.SH AUTHOR
heatherly <jelloshrke at gmail dot com>

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster

