.TH gyges 5 2013-Jan "linux" "heatherly custom tools manual"

.SH NAME
gyges_hekatonkheires \- structure of the gyges spreadsheet file

.SH IMAGERY (see HERITAGE at bottom for more)
ugly, impossibly powerful, one-hundred handed, fifty headed giant

.SH SUMMARY
gyges (j-eye-j-ees) is a light, clean, powerful, technical, aesthetic, and
keyboard-centric console spreadsheet focused on functionality, analytics,
interfacing, scripting, and tailored usage.









.SH SEE ALSO
this documentation is layered to provide easier navigation.
   gyges (1), initiation, options, and structure
   gyges (5), structure of the gyges spreadsheet file
   gyges (6), interactive system usage and navigation
   gyges (7), decision rationale, objectives, and overview
   yVIKEYS, undestanding the VIKEYS standard
   yURG, understanding the available tracing and debugging

.SH AUTHOR
heatherly <jelloshrke at gmail dot com>

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster

