.TH gyges 6 2013-Jan "linux" "heatherly custom tools manual"

.SH NAME
gyges_hekatonkheires \- interactive system usage and navigation

.SH IMAGERY (see HERITAGE at bottom for more)
ugly, impossibly powerful, one-hundred handed, fifty headed giant

.SH SUMMARY
gyges (j-eye-j-ees) is a light, clean, powerful, technical, aesthetic, and
keyboard-centric console spreadsheet focused on functionality, analytics,
interfacing, scripting, and tailored usage.

.SH KEYBOARD MACROS
gyges implements keyboard macros exactly according to the yVIKEYS standard.
to review the standard, use "man 6 yVIKEYS" and search for the "keyboard
macros" section.  below are some gyges specifics...

.B modes.  
recording (q) and execution (@) keys are only available in map and god mode.
to finish recording, make sure to exit source or input modes.

.B editing.  
keyboard macros are saved on tab Z in the first 26 rows -- name in col A and
macro in col B.  you can edit them like any other text string cell.

.B computed contents.  
the keyboard macro can be the result of string formulas.  gyges will then
take the result and execute it.

.B copy, paste, and transfer.  
since keyboard macros are stored as odinary text in normal cells, you can
use any gyges select, copy, paste, and register exporting to transfer them.


.SH SEE ALSO
this documentation is layered to provide easier navigation.
   gyges (1), initiation, options, and structure
   gyges (5), structure of the gyges spreadsheet file
   gyges (6), interactive system usage and navigation
   gyges (7), decision rationale, objectives, and overview
   yVIKEYS, undestanding the VIKEYS standard
   yURG, understanding the available tracing and debugging

.SH AUTHOR
heatherly <jelloshrke at gmail dot com>

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster

