.TH gyges 1 2013-Jan "linux" "heatherly custom tools manual"

.SH NAME
gyges_hekatonkheires \- interactive system usage and navigation

.SH IMAGERY (see HERITAGE at bottom for more)
ugly, impossibly powerful, one-hundred handed, fifty headed giant

.SH SUMMARY
gyges (j-eye-j-ees) is a light, clean, powerful, technical, aesthetic, and
keyboard-centric console spreadsheet focused on functionality, analytics,
interfacing, scripting, and tailored usage.

.SH SCOPE, REASONING and DECISION

.B situation (s).  
spreadsheets are a modern wonder of interactive calculation, iterative design,
and complex analysis which can be quite reasonably and economically placed
in the hands of non-technical users.

.B complication (c).  
raging acceptance led to uncontrolled creeping featurism and kitchen-sink
capabilities -- replacing everything from todo lists, graphing, database
management and some production systems.  these systems are now fat, expensive,
and hard to use efficiently.

.B problem (p).  
spreadsheets are now simply magic -- too many capabilities and flexility
combined with complex problems and spaghetti solutions.  none of the safety,
debugging, and testing seem to apply.  i need more -- a fast, light, adaptable,
portable spreadsheet solution.

.B my solution (m).  
tight, keyboard-centric, power-user focused custom solution.  do one thing
and do it well.  pare back funtionality to a core feature set which can be
fully understood and tested, hand off non-core to other tools, and make the
interface more productive.

.B target user (t).  
very technical, well-versed, power user.

.B accepted functionality (a).  
   -- conceptual framework of cells within tabs within sheets
   -- full vi-keys support and a majority of vi/vim features
   -- console/terminal formatting to enforce value and focus
   -- full set of mathmatical operators for functions
   -- full set of core functions, as in lotus, visicalc, and excel
   -- dependency-graph calculation method to avoid issues
   -- cell coloring for interpretation and dependency-awareness
   -- compile calculations to byte-code for speed
   -- fully scriptable using the same commands

.B rejected functionality (r).  
   -- mouse and touchscreen (fuck off)
   -- any formatting other than alignment and numerical
   -- graphing or visual analyses (integrate with other tools)
   -- importing or exporting of special formats (like xls, etc)
   -- large data tables (which should be in a controlled database)
   -- data sorting and filtering (again, database)
   -- reporting and printing (just not a spreadsheet thing)
   -- cell notes to provide details
   -- text wrapping (learn word processors or databases)

.B as always, all my applications must (#).  
   -- run on any linux box from raspberry to cray
   -- stay focused, small, tight, reliable, and secure
   -- forgo sloppy, kitchen-sink languages, like python, java, or perl
   -- stay away from dependency on external code libraries, like boost
   -- only human-readable, 7-bit safe, ascii streams (not database)
   -- have dedicated, maintained, automated unit testing
   -- provide either detailed reporting or logging for debugging
   -- use secure communications between systems where required
   -- clean, clean code so i can maintain after long absences
   -- no international, multi-lang, multi-byte support (freaking ever)
   -- one-hundred percent keyboard driven and centric
   -- operate using modes and windows/panels like vi/vim
   -- follow the yVIKEYS standard to the letter

.SH HERITAGE
.B background.  
gyges, the big-limbed, is the youngst of three primeval giant brothers
called the hekatonkheires (hundred-handed).  each brother was extremely
powerful, more powerful than all the titans combined.  and, were impossibly
ugly in a way only something with one-hundred hands and fifty heads can be.

.B parentage.  
these brothers were born of ouranos (father-sky) and gaia (mother-earth).

.B why use this imagery.  
this spreadsheet is named after gyges given the extremely powerful, massively
parallel, and dangerously unconstrained nature of the spreadsheet concept.

.SH SEE ALSO
this documentation is layered to provide easier navigation.
   gyges (1), initiation, options, and structure
   gyges (5), structure of the gyges spreadsheet file
   gyges (6), interactive system usage and navigation
   gyges (7), decision rationale, objectives, and overview
   yVIKEYS, undestanding the VIKEYS standard
   yURG, understanding the available tracing and debugging

.SH AUTHOR
heatherly <jelloshrke at gmail dot com>

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster

