#! /bin/gyges
##
## yVIKEYS script to create the voyager spreadsheet for demonstration
##
## demo uses "shrike" font, and 101 columns by 43 lines
##
##   this is a very common size for my keybindings configuration
##
##   best viewed if terminal is set to COLUMNS=101 or slightly more
##   and LINES=43 or slightly more
##
##   different for other systems, but i can for fluxbox/X11 to exact settings using
##      º:myhome  600 100¦»
##      º:mysize  615 435¦»
##   obviously this is a little system dependent, but i keep hardware a long time ;)
##

###<<< BLITZ

º··µre5··»

{
   :note #¦
   :myhome 675 100¦
   :mysize 619 443¦
   :0p29¦··+1¦··l+1¦··l+1¦··l+1¦··l-1¦··
   :0p30¦··s ¦··ls  5¦··
   :0p34¦··s=p29+5¦··
   0_
}
###<<< SCREEN_PRINT unit_ymacro_voyager_1.scrn


##==[[ header statement ]]====================================================##
º:0a1¦·······swhere is the voyager 1 spacecraft (90 sec)?¦···············································11(ls<¦)··»
º··0··v·11l··»
## ÏÏÏÏÏ·ÏÏÏÏÏ
ÏÏ

º··¥··0··2j··sa friend of mine stunned me recently.  he said, a major news channel reported that the¦····11(ls<¦)··»
º··¥··0···j··svoyager spacecraft had returned signals from numerous stars it had already passed.¦········11(ls<¦)··»
º··¥··0···j··sthe reporter was then confidently making pronouncements and uncovering conspiracies !?!¦···11(ls<¦)··»
º··¥··0···j··»
## ÏÏÏÏÏ·ÏÏÏÏÏ ÏÏÏÏÏ·ÏÏÏÏÏ
ÏÏÏÏ


###<<< SCREEN_PRINT unit_ymacro_voyager_2.scrn


##==[[ titles ]]==============================================================##


º·:0a12¦·····sstart with some headers¦··f|··4(ls<¦)··»
º·0···j······sand column sizing to¦·····f|··4(ls<¦)··»
º·0···j······sorganze.¦R················f|··4(ls<¦)··»
º·:0a8¦·»
## ÏÏÏÏÏ·ÏÏÏÏÏ
ÏÏ

·····ssubject¦··········F·w····-^¦
l····syear¦·············F·wl···-^¦
l····sday¦··············F·whhh·-^¦
l····shour¦·············F·Nll··-^¦
l····smin¦··············F·Nl···-^¦
l····ssec¦··············F·nll··-^¦
0·j

ºv··5j5l··x··v··5j5l··x»
º2jl···snow add scaling values¦···f|··ls<¦»
ºjh····sto convert between¦·······f|··ls<¦»
ºjh····sthese time units.¦········f|··ls<¦»
º04k»

·····sscales (per)¦
2l···+365¦··············f|
l····+24¦···············f|
l····+60¦···············f|
l····+60¦···············f|
º0j··v··3j5l··x··v··3j5l··x»
## ÏÏÏÏÏ·ÏÏÏÏÏ
ÏÏ


##==[[ legend ]]==============================================================##

º·:0c26¦··sWARNING, simplistic mathematical projections¦········F|¦··································3(ls<¦)··»
º··j·3h···s(directionally correct only)¦························F|¦··································3(ls<¦)··»

º·:0d29¦··sAUTOMATIC TEXT COLORATION¦···························F|_¦·································2(ls<¦)··»
º·:0c30¦··+1¦···················································l··sblue are numerical constants¦····2(ls<¦)··»
º·3h·j····=`k¦+1¦···············································l··sgreen are calculated numbers¦····2(ls<¦)··»
º·3h·j····=0p29+0q29+0r29+0s29+0t29+0q29-0r29+0s29+0t29+5-5¦····l··sred are complicated formulas¦····2(ls<¦)··»
º·3h·j····s 4¦··········f>······································l··sbrown are text constants¦········2(ls<¦)··»
º·3h·j····#0p30µ_d0q30¦·f>······································l··spurple are text formulas¦········2(ls<¦)··»
º·3h·j····s~p34¦········f>······································l··smagenta are reused formulas¦·····2(ls<¦)··»
## ÏÏÏÏÏ·ÏÏÏÏÏ
ÏÏ


###<<< SCREEN_PRINT unit_ymacro_voyager_3.scrn


##==[[ speeds ]]==============================================================##

:a11¦·····slight miles¦···L····+186282¦·······fc

º·2j·2h···sthis formula is being built¦·····2(ls<¦)··»
º··j·2h···sby moving/wandering not¦·········2(ls<¦)··»
º··j·2h···styping directly.¦················2(ls<¦)··»
º·4k··h··»

=Ï`ÏlÏ*ÏkÏkÏ'Ï¦Ï¦····fc


º·2j·3h··sthen, cut/paste across¦·············ls<¦··»
º··j··h··swith automatic formula¦·············ls<¦··»
º··j··h··stransformations.¦···················ls<¦··»

·4k·Ï·2l·Ï·y·Ï·3(hÏpÏ)

º·2j··v··2j4l··x··v··2j4l··x»

º··0·····sgreen background means¦·····f|······ls<¦··»
º··j··h··sthis value is needed¦·······f|······ls<¦··»
º··j··h··sby current cell.¦···········f|······ls<¦··»

º·2k··l··syellow marks¦···············f|··»
º··j·····sthe current¦················f|··»
º··j·····scell.¦······················f|··»

º··l·2k··spurple background means¦····f|····2(ls<¦)··»
º··j·2h··sthis cell provides info¦····f|····2(ls<¦)··»
º··j·2h··sto the current cell.¦·······f|····2(ls<¦)··»

º·4h·4k·»
l
## ÏÏÏÏÏÏÏ
ÏÏÏ


###<<< SCREEN_PRINT unit_ymacro_voyager_4.scrn



º·2j··0··v··2j5l··x··v··2j5l··x··2k»

º·2l·7j··svoyager is 20,000 times¦·······f|··ls<¦··»
º··j··h··sSLOWER than light (0.006c).¦···f|··ls<¦··»
º·8k·h··»

0j···ºs  voyager miles¦»
3l···+38610¦············fc
l····=Ï`ÏhÏ/ÏkÏkÏkÏlÏ'Ï¦Ï¦·····fc··y·ÏÏ·l··p

·3h·k··y···j····p
··h····p

·0··j···ºs  speeding bullet¦»
···3l····+682¦··············fc
····l··k···y·j·p

l····p··················fg
hhhk·y
j····p
h····p

0j···ºs  usain bolt¦»
lll··+27¦···············fc
lk···y·j·p··············fg
l····p··················fg
hhhk·y
j····p
h····p

º4jl··v··j2l··x··v··j2l··x··4kh»

##==[[ sun ]]=================================================================##
0jj·ºsour sun (one au)¦»

º7j····svoyager takes 100 days to¦·····f|··ls<¦»
ºjh····stravel 1au vs light in 8min.¦··f|··ls<¦»
º8k0»

l····+9.295Ë7¦··········fc

0j···ºslight¦············f>»
l····=`k'''/kkkkk.¦¦····fG··y
l····p··················fG
l····p··················fg
l····p··················fg
l····p··················f0

0j···ºsvoyager¦··········f>»
llk··y·j·p

0j···ºsbullet¦···········f>»
l····p

0j···ºsusain¦············f>»
l····p

º3jh·v··jl··x··v··jl··x··3k0»

###<<< SCREEN_PRINT unit_ymacro_voyager_5.scrn



##==[[ closest start ]]=======================================================##
0jj··ºsproxima centari¦»

º6j0···sthis star is the closest to¦··f|··ls<¦»
º0j····searth in ANY direction.¦······f|··ls<¦»
º7k0»

lj···+4.2¦··············Ff1¦
k····=`j*kkkkkkkkkkkk¦¦···fc

0j···ºslight¦············f>»
ll···=`kh'''/11kl.¦¦····fc··y
l····p··················fc
l····p··················fc

0j···ºsvoyager¦··········f>»
llk··y·jh·p·············Fc0¦

0j···ºshuman gens¦······f>»
º·0·3j··xl··xl·»
º·0··j··si'll guess 25yrs each on an¦···f|··ls<¦»
º·0··j··sinterstellar spacecraft¦·······f|··ls<¦»
º·0·5k·»
l····=`k¦/25¦···········fc
# ÏÏ
Ï

º3j0··v··3jl··x··v··2jl··x»
º3k»

##==[[ first star ]]==========================================================##
0jj··ºsgliese 445¦»

º6j0···sthis is the star voyager¦········f|··ls<¦»
º0j····swill ACTUALLY pass nearest¦······f|··ls<¦»
º0j····s(not close by, ~2 light years)¦··f|··ls<¦»
º8k0»

lj···+17.1¦·············Ff1¦
k····=`j*17k¦¦··········fc

0j···ºslight¦············f>»

0j···ºsvoyager¦··········f>»
l····=`2k/15k¦¦·········fc

0j···ºshuman gens¦······f>»
l····=`k¦/25¦···········fc

º3j0··v··2jl··x··v··2jl··x»
º3k»


###<<< SCREEN_PRINT unit_ymacro_voyager_6.scrn




##==[[ now ]]=================================================================##
0jj··ºsvoyager NOW (years)¦»
l····+43¦

0j···ºsmiles so far¦·····f>»
l····=`k*20k¦¦··········fc

0j···ºspercent done¦·····f>»
l····=`k/6k¦*100¦·······fg




##==[[ footer quote ]]========================================================##
º:0a37¦»
ºsspace is big.  really big.  you just won't believe how vasty, hugely, mindbogglingly big.¦»
ºl··s<¦··y··lp··lp··lp··lp»
º0j·s  -- hitchhiker's guide to the galaxy by the one-and-only douglas adams (noted futurist ;)¦»
ºl··s<¦··y··lp··lp··lp··lp»



º_0··v5l»


###<<< SCREEN_PRINT unit_ymacro_voyager_7.scrn

